# Generated by Django 4.0 on 2024-06-06 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module6stockretail',
            name='average_price_per_bag',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=120, null=True),
        ),
    ]
