# Generated by Django 4.0 on 2024-04-28 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companybooking',
            old_name='cusomer_innovoice_number',
            new_name='customer_innovoice_number',
        ),
    ]
