# Generated by Django 4.0 on 2024-07-04 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_module6stockretail_average_price_per_bag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module4',
            old_name='amount',
            new_name='balance',
        ),
        migrations.RemoveField(
            model_name='module4',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='stockout',
            name='borrow',
        ),
    ]
