# Generated by Django 4.0 on 2024-04-29 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_cusomer_innovoice_number_companybooking_customer_innovoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='companybooking',
            name='Diversion_Company_Bookings',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='companybooking',
            name='per_bag_price',
            field=models.CharField(blank=True, max_length=122, null=True),
        ),
    ]
