# Generated by Django 4.0 on 2024-04-29 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_companybooking_diversion_company_bookings_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companybooking',
            old_name='Diversion_Company_Bookings',
            new_name='Diversion_Party',
        ),
    ]
