# Generated by Django 4.0 on 2024-04-30 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_diversion_company_bookings_companybooking_diversion_party'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='Diversion_Party',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='per_bag_price',
            field=models.CharField(blank=True, max_length=122, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='remaining_bags',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
