# Generated by Django 5.0.7 on 2024-08-20 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_module4_again_customer_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='companybooking',
            name='total_dispatch',
            field=models.CharField(default='', max_length=115),
            preserve_default=False,
        ),
    ]
