# Generated by Django 5.0.7 on 2024-08-20 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_companybooking_total_dispatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockindata',
            name='product',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
