# Generated by Django 4.0 on 2024-04-30 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_deal_diversion_party_deal_per_bag_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='diversion_bags',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
