# Generated by Django 5.0.7 on 2024-08-21 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_stockindata_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='total_dispatch',
            field=models.CharField(default='', max_length=115),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module3',
            name='total_dispatch',
            field=models.CharField(default='', max_length=115),
            preserve_default=False,
        ),
    ]
