# Generated by Django 5.0.7 on 2024-08-21 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_deal_delivered_bags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module3',
            name='delivered_bags',
        ),
    ]
